### ISSUE TITLE
Malformed payload errors using Azure Event Hub on receipt of multi-frame messages

### ISSUE THREAD

**Issue by ianwsperber** [noodlefrenzy/node-amqp10#178]
I'm populating an Azure event hub using a stream analytics job and attempting to read from the event hub using this library. The library chokes on certain events with error messages like:

`malformed payload: Unknown code prefix: 0x30`
`malformed payload: Unknown code prefix: 0x20`
`malformed payload: Unknown code: 0x64`
`malformed payload: Unable to decode bytes from message body: 005375b00002810c5b7b226576656e7474797065223a2254656c656d65747279507573684576656e74222c2270....`

Any ideas on what could be wrong?

**Comment by mbroadst** [comment]
@ianwsperber is it possible to get a debug dump of your session? (as in specifying `DEBUG=amqp*` as an environment variable when  you run your script)

**Comment by ianwsperber** [comment]
Here's a sample from the logs (had to clean up a little since the information is sensitive):

```
malformed payload: Unable to decode bytes from message body: 005375b00003ef795b7b2265766.....a3232333034302c2274797065
malformed payload: Unknown code prefix: 0x20
malformed payload: Unknown code prefix: 0x30
malformed payload: Unknown code prefix: 0x20
malformed payload: Unable to decode bytes from message body: 005375b00003ef5e5b7b2265766.....a34363a31352e303030303030
malformed payload: Unable to decode bytes from message body: 005375b00003ef165b7b2265766.....172746e65726e6f7469666963
malformed payload: Unknown code prefix: 0x30
malformed payload: Unknown message contents: 29801
malformed payload: Unknown code prefix: 0x30
malformed payload: Unknown code prefix: 0x30
malformed payload: Unknown code prefix: 0x30
malformed payload: Unknown code prefix: 0x30
malformed payload: Unable to decode bytes from message body: 005375b00002bf345b7b2265766.....964223a3234393830302c2274
malformed payload: Unknown code: 0x79
malformed payload: Unknown code prefix: 0x20
malformed payload: Unable to decode bytes from message body: 005375b00002810c5b7b2265766.....23a34322e333239333736322c
malformed payload: Unknown code prefix: 0x20
malformed payload: Unknown code: 0x64
malformed payload: Unable to decode bytes from message body: 005375b00003eef95b7b2265766.....2333034302c2274797065223a
malformed payload: Unknown code prefix: 0x20
malformed payload: Unknown code prefix: 0x30
malformed payload: Unknown message contents: 28263
malformed payload: Unable to decode bytes from message body: 005375b00003efee5b7b2265766.....d39332e353735353834342c22
UTF32 not yet implemented
UTF32 not yet implemented
malformed payload: Unknown code prefix: 0x20
```

**Comment by mbroadst** [comment]
@ianwsperber I understand the need to protect the data, we appreciate whatever clues we can get to the bottom of the issue. For starters, I've added very basic support for the AMQP `char` type (which is utf32be, not something node is natively very happy with). I've pushed that to the `char-support` branch. Would you mind trying your test again with that in place?

If you're unclear how to test that branch, you simply need to modify your `package.json` like so:
```
"dependencies": {
   ... other dependencies ...,
   "amqp10": "noodlefrenzy/node-amqp10#char-support"
}
```

**Comment by ianwsperber** [comment]
Changed the reference in the package.json and reinstalled, didn't fix the error

**Comment by mbroadst** [comment]
@ianwsperber thanks for testing that out, would it be possible to get an updated debug output from there? Clearly some piece of data is clobbering our codec, and my hunch is that is why you are getting so many errors regarding unknown code prefixes, because the codec failed to increment its internal buffer pointer.

Trying to isolate the particular piece of incoming data that first triggers this failure is probably the fastest way to a fix. Would it be possible to run this against less sensitive data in order to get a more complete trace log?

**Comment by ianwsperber** [comment]
@mbroadst Sure thing! I won't be able to now but sometime early next week I'll throw some dummy data into our event hub and send you the complete output

**Comment by mbroadst** [comment]
@ianwsperber thanks a lot! @noodlefrenzy should be back from his adventures over seas by then, and he's way more familiar with SB/EH than I am - hopefully together we can knock this one out

**Comment by noodlefrenzy** [comment]
Hey, sorry, I'm back now. @ianwsperber can I ask - what does the payload look like of the streaming analytics job you're using? The default decoder used by the Event Hub policy assumes that any binary data coming in is a JSON string and tries to parse it, as that's typically the format used by the C# EventHub SDK. (see https://github.com/noodlefrenzy/node-amqp10/blob/master/lib/policies/service_bus_policy.js).

Also, @mbroadst is correct in that it looks like it's getting confused in the codec - I'd love to see the entire binary payload of the Transfer frame from your logs if and when you can send some non-sensitive messages through.

**Comment by ianwsperber** [comment]
@noodlefrenzy @mbroadst I haven't yet had a change to send non-sensitive information through our event hub, but we've had an azure support dev looking at the issue and he went ahead and did some investigatory work. He sent over the below snippet detailing some of his research and I thought it may be helpful.

Like I said, the data is sensitive so I've had to delete most the message body, but I've left the head iof the message, where the library is erroring out. I'll still try to get some non-sensitive information into our eventhub and send over our logs for that.

```
#I’ve been able to extract the first message that fails decoding:

[root@u15 node-amqp10]# node cx-recv.js > bad.packet 2>&1
 
[root@u15 node-amqp10]# head bad.packet
malformed payload: Unable to decode bytes from message body: 005375b00003ef165b7 [...]

[..]
 
# hex -> ascii

[root@u15 node-amqp10]# xxd -r -p bad.packet

Su▒▒[{"eventtype":"TelemetryPushEvent", [...] "timestamp":"2015-10-19T20:47:49.0000000Z"}

[..]

[root@u15 node-amqp10]# xxd -r -p firstbytes
Su▒▒[{"eventtype":"Tele

# after trimming everything after “Su▒▒” in “firstbytes”
[root@u15 node-amqp10]# cat firstbytes
005375b00003ef
 
# high chance this is the offending byte sequence
[root@u15 node-amqp10]# xxd -r -p firstbytes
Su▒▒

# I don’t know if this is garbage from ingress point or an encoding problem or just node-amqp10 exception handling printing bytes that were never present in the message in the first place,
```

**Comment by mbroadst** [comment]
@ianwsperber thanks for the feedback, I see where our codec is being tripped up I just don't know how to feed it data to reproduce your result. This may be a bit much to ask, but is it possible for you to take the `bad.packet` file and simply fill in fake data for the sensitive information?

As a sort of last ditch effort, @noodlefrenzy actually works at that company and could probably get access to the data under NDA perhaps?

**Comment by snobu** [comment]
I did the hex analysis above, @noodlefrenzy and i both work for "that" undisclosed company:)
If @ianwsperber agrees, i can share internally the raw bad actors. I think we're very close to finding the _what_. And then it's probably just a matter of hours until we find the _why_ and a patch is committed.

**Comment by mbroadst** [comment]
@snobu yeah I think it would really be as easy as feeding the right buffer into a test for the codec. For instance if you added something like:

```
    it('should decode this <thing>', function() {
      var buffer = newBuffer([
         0x00, 0x53, 0x75, 0xb0, 0x00, 0x03, 0xef, 0x16, 0x5b, 0x7, 0x7, 0x7, 0x7, 0x7, 0x7, 0x7
      ]);
      var actual = codec.decode(buffer);
    });
```

to [this file](https://github.com/noodlefrenzy/node-amqp10/blob/master/test/unit/test_codec.js#L21) and get the same output as above, we'd have a really solid starting point for fixing the problem. As I suggested above, if you're able to do that then you're probably also at that point able to substitute the sensitive data with some filler as well. At that point we should very easily be able to solve the problem :smile:

**Comment by snobu** [comment]
```bash
[root@u15 test]# cat encoding/test_badactor.js

'use strict';

var Int64 = require('node-int64'),
    expect = require('chai').expect,
    Builder = require('buffer-builder'),
    codec = require('../../lib/codec'),
    tu = require('../unit/testing_utils');

var newBuffer = tu.newBuffer;

describe('Codec', function() {
  describe('Decoder test', function() {
    it('Decode me if you can', function() {
      // malformed packet
      // 0x00, 0x53, 0x75, 0xb0, 0x00, 0x03, 0xef, 0x16,
      var buffer = newBuffer([
         0x00, 0x53, 0x75, 0xb0, 0x00, 0x03, 0xef, 0x16, 0x5b, 0x7b, 0x22, 0x65, 0x76, 0x65, 0x6b, 0x74,
         0x74, 0x79, 0x70, 0x65, 0x22, 0x3a, 0x22, 0x54, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79,
         0x22, 0x7d, 0x5d, 0x0a
      ]);

      var actual = codec.decode(buffer);

      console.log('\t\t buffer = ' + buffer);
      console.log('\t\t codec.decode(buffer) = ' + codec.decode(buffer));

      // Not sure what to expect but it doesn't really matter
      // since the decoding fails before we hit this line
      expect(actual.to.have.any.keys('eventtype'));
    });
  });
});
```

```bash
[root@u15 test]# mocha encoding

  Codec
    Decoder test
                 buffer = Su��[{"evekttype":"Telemetry"}]

                 codec.decode(buffer) = undefined
      1) Decode me if you can


  0 passing (65ms)
  1 failing

  1) Codec Decoder test Decode me if you can:
     TypeError: Cannot read property 'to' of undefined
      at Context.<anonymous> (encoding/test_badactor.js:27:20)
```

Am I doing this right?

**Comment by mbroadst** [comment]
getting closer:
* `expect(actual.to.have.any.keys('eventtype'));` should be `expect(actual).to.have.any.keys('eventtype');` 
* we still don't have quite enough data to properly test this (though I'm going to go ahead and try to just fill in some fake data). According to the spec, the way this is read is:
   * `0x00` is encountered indicating its a 'constructor'
   * At this point we read in two bytes, in this case `0x53 0x75`, indicating its a described type and the length is `0x75` (or 117)
   * You're getting a result of `undefined` because there isn't an additional 117 bytes of data left in the buffer

**Comment by mbroadst** [comment]
hmm yeah, beyond that the variable length of the binary data sent is actually 257819 in this case.. Are these telemetry messages pretty huge? Or is it likely this data is corrupted before it's making it to the bus?

**Comment by snobu** [comment]
They look quite big to me, so 250 KB looks to be the real deal.

I get the same thing:
```
  amqp10:client Reading variable with prefix 0xb0 of length 257819 +0ms
         actual = undefined
         buffer = Su��[{"eventtype":"Telemetry"}]
````

**Comment by snobu** [comment]
Is there a snippet I could use to print to length before attempting to decode the thing?

**Comment by snobu** [comment]
~~They look quite big to me, so 250 KB looks to be the real deal.~~

Scratch that. The messages that I am able to decode are under 10KB or so. So it could be just a matter of size.

Let's try to build a test for a really big payload? Not sure if AMQP defines a MAX message length, I tried to grep though the spec but it's humongous.

**Comment by mbroadst** [comment]
The codec seems to be handling this just fine, if I change the test case to:
```
var rawBuffer = [
    0x00, 0x53, 0x75,
    0xb0, 0x00, 0x03, 0xef, 0x16, 0x5b, 0x7b, 0x22, 0x65, 0x76, 0x65, 0x6b, 0x74,
    0x74, 0x79, 0x70, 0x65, 0x22, 0x3a, 0x22, 0x54, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x74, 0x72, 0x79,
    0x22, 0x7d, 0x5d, 0x0a,
];

var extraByteCount = (257819 + 8 - rawBuffer.length);
// 257819 is the size we want for the data segment
// 8 is the size of the informational bytes before the data segment

for (var i = 0; i < extraByteCount; ++i) rawBuffer.push(0x00);
var buffer = newBuffer(rawBuffer);
var actual = codec.decode(buffer);
console.log('codec.decode(buffer) = ', actual);
```

then I get the following result:
```
[ { descriptor: [Int64 value:117 octets:00 00 00 00 00 00 00 75],
    value: <Buffer 5b 7b 22 65 76 65 6b 74 74 79 70 65 22 3a 22 54 65 6c 65 6d 65 74 72 79 22 7d 5d 0a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ... > },
  257822 ]
```

It's _possible_ you have data in the binary segment thats corrupting the stream somehow but it seems unlikely. In those cases we simply slice the descriptive bytes off the top and return the raw buffer, so there's very little we could screw up there. 

Perhaps we could get more information about the "nature" of the payload. 
  * First of all, it seems to be large chunks of text (perhaps JSON) transmitted as binary data, correct? 
  * Are there multiple body segments? We don't currently handle that case very well, as nobody has run into it.
  * While you've identified a screwed up string in the data, you might start scanning _before_ that piece of text and see if you can find something amiss. The spec is indeed pretty large, but the quick description I've given above regarding the `constructors` should be somewhat easier to spot.

**Comment by mbroadst** [comment]
Actually upon a second glance this does indeed still look screwed up, the descriptor is out of whack - it almost looks like the constructor is trying to use a binary type as the descriptor.

@noodlefrenzy do you have any thoughts?

**Comment by snobu** [comment]
Here's how the message looks like - the one that fails decoding - (sanitized, decoded from the Exception printout):

```json
[
  {
    "key1": 1111,
    "eventtype": "TelemetryPushEvent",
    "key3": 11,
    "key4": 11,
    "key5": 11,
    "key6": 11,
    "partitionkey": 123456,
    "key7": 11,
    "key8": 11.11,
    "timestamp": "201X-XX-XXT2X:XX:XX.0000000Z",
    "key10": "ascii string"
  },
  {
    "key1": 2222,
    "eventtype": "TelemetryPushEvent",
    "key3": 22,
    "key4": 22,
    "key5": 22,
    "key6": 22,
    "partitionkey": 234567,
    "key7": 22,
    "key8": 22.22,
    "timestamp": "201X-XX-XXT2X:XX:XX.0000000Z",
    "key10": "ascii string"
  },
  {
    "key1": 3333,
    "eventtype": "TelemetryPushEvent",
    "key3": 33,
    "key4": 33,
    "key5": 33,
    "key6": 33,
    "partitionkey": 345678,
    "key7": 33,
    "key8": 33.33,
    "timestamp": "201X-XX-XXT2X:XX:XX.0000000Z",
    "key10": "Location"
  }
  .. repeats 241 more times .. probably more as it ends mid-keyname
  (i'm guessing the exception handling has a limit on the number of bytes
  it will print from the bad actor)
]
```

**Comment by mbroadst** [comment]
@snobu unfortunately its not an issue with our handling of large binary segments, the following code works perfectly:

```
    it('should encode/decode a large binary dataset', function() {
      var generate = function(num) {
        return {
          key1: num * 1000,
          eventtype: "TelemetryPushEvent",
          key3: num,
          key4: num,
          key5: num,
          key6: num,
          partitionkey: 123456,
          key7: num,
          key8: num + 0.25,
          timestamp: "201X-XX-XXT2X:XX:XX.0000000Z",
          key10: "ascii string"
        };
      };

      var objects = [];
      for (var i = 0; i < 241; ++i) {
        objects.push(generate(i + 1));
      }

      var encoded = new Builder();
      codec.encode(new Buffer(JSON.stringify(objects)), encoded);

      var decoded = codec.decode(encoded.get());
      var decodedJson = JSON.parse(decoded[0].toString());
      expect(decodedJson).to.eql(objects);

    });
```

The anomaly here is the injection of this constructor `0x00, 0x53, 0x75` before the binary definition `b0`. What client is being used to generate/populate the data?

**Comment by snobu** [comment]
No idea. @ianwsperber may know.

**Comment by snobu** [comment]
Trying to read from Event Hub in debug mode shows additional useful addition info. @ianwsperber let me know if it's ok to share the data internally with @noodlefrenzy

**Comment by snobu** [comment]
Not sure if this stuff is synchronous or it's async and doesn't really mean much but maybe it helps?

```bash
[root@u15 node-amqp10]# echo $DEBUG
amqp*
```

```
Mon, 02 Nov 2015 14:50:17 GMT amqp10:client Reading variable with prefix 0xa0 of length 14
Mon, 02 Nov 2015 14:50:17 GMT amqp10:client Decoding a30c782d6f70742d6f6666736574
Mon, 02 Nov 2015 14:50:17 GMT amqp10:client Reading variable with prefix 0xa0 of length 7
Mon, 02 Nov 2015 14:50:17 GMT amqp10:client Decoding a1053131353638
Mon, 02 Nov 2015 14:50:17 GMT amqp10:client Reading variable with prefix 0xa0 of length 21
Mon, 02 Nov 2015 14:50:17 GMT amqp10:client Decoding a313782d6f70742d656e7175657565642d74696d65
Mon, 02 Nov 2015 14:50:17 GMT amqp10:client Decoding 830000015096222212
Mon, 02 Nov 2015 14:50:17 GMT amqp10:client Reading variable with prefix 0xb0 of length 257918
malformed payload: Unable to decode bytes from message body: 005375b00003ef795b7b226576656e747479...

-------------------------------------------------------------------------------------------------------

Mon, 02 Nov 2015 14:50:17 GMT amqp10:client Decoding a315782d6f70742d73657175656e63652d6e756d626572
Mon, 02 Nov 2015 14:50:17 GMT amqp10:client Decoding 5501
Mon, 02 Nov 2015 14:50:17 GMT amqp10:client Reading variable with prefix 0xa0 of length 14
Mon, 02 Nov 2015 14:50:17 GMT amqp10:client Decoding a30c782d6f70742d6f6666736574
Mon, 02 Nov 2015 14:50:17 GMT amqp10:client Reading variable with prefix 0xa0 of length 7
Mon, 02 Nov 2015 14:50:17 GMT amqp10:client Decoding a1053131353638
Mon, 02 Nov 2015 14:50:17 GMT amqp10:client Reading variable with prefix 0xa0 of length 21
Mon, 02 Nov 2015 14:50:17 GMT amqp10:client Decoding a313782d6f70742d656e7175657565642d74696d65
Mon, 02 Nov 2015 14:50:17 GMT amqp10:client Decoding 830000015096222212
Mon, 02 Nov 2015 14:50:17 GMT amqp10:client Reading variable with prefix 0xb0 of length 257918
malformed payload: Unable to decode bytes from message body: 005375b00003ef795b7b226576656e747479706...

-------------------------------------------------------------------------------------------------------

Mon, 02 Nov 2015 14:50:35 GMT amqp10:client Decoding a315782d6f70742d73657175656e63652d6e756d626572
Mon, 02 Nov 2015 14:50:35 GMT amqp10:client Decoding 810000000000000088
Mon, 02 Nov 2015 14:50:35 GMT amqp10:client Reading variable with prefix 0xa0 of length 14
Mon, 02 Nov 2015 14:50:35 GMT amqp10:client Decoding a30c782d6f70742d6f6666736574
Mon, 02 Nov 2015 14:50:35 GMT amqp10:client Reading variable with prefix 0xa0 of length 9
Mon, 02 Nov 2015 14:50:35 GMT amqp10:client Decoding a10731323732353532
Mon, 02 Nov 2015 14:50:35 GMT amqp10:client Reading variable with prefix 0xa0 of length 21
Mon, 02 Nov 2015 14:50:35 GMT amqp10:client Decoding a313782d6f70742d656e7175657565642d74696d65
Mon, 02 Nov 2015 14:50:35 GMT amqp10:client Decoding 8300000150a5102fc9
Mon, 02 Nov 2015 14:50:35 GMT amqp10:client Reading variable with prefix 0xb0 of length 152897
malformed payload: Unable to decode bytes from message body: 005375b00002553c5b7b226576656e7474797065223a2254656c65...

-------------------------------------------------------------------------------------------------------

Mon, 02 Nov 2015 14:50:34 GMT amqp10:client Decoding a315782d6f70742d73657175656e63652d6e756d626572
Mon, 02 Nov 2015 14:50:34 GMT amqp10:client Decoding 810000000000000087
Mon, 02 Nov 2015 14:50:34 GMT amqp10:client Reading variable with prefix 0xa0 of length 14
Mon, 02 Nov 2015 14:50:34 GMT amqp10:client Decoding a30c782d6f70742d6f6666736574
Mon, 02 Nov 2015 14:50:34 GMT amqp10:client Reading variable with prefix 0xa0 of length 9
Mon, 02 Nov 2015 14:50:34 GMT amqp10:client Decoding a10731303134353434
Mon, 02 Nov 2015 14:50:34 GMT amqp10:client Reading variable with prefix 0xa0 of length 21
Mon, 02 Nov 2015 14:50:34 GMT amqp10:client Decoding a313782d6f70742d656e7175657565642d74696d65
Mon, 02 Nov 2015 14:50:34 GMT amqp10:client Decoding 8300000150a50fffc2
Mon, 02 Nov 2015 14:50:34 GMT amqp10:client Reading variable with prefix 0xb0 of length 257955
malformed payload: Unable to decode bytes from message body: 005375b00003ef9e5b7b226576656e7474797065223a2254656c656d65747279....

-------------------------------------------------------------------------------------------------------

Mon, 02 Nov 2015 14:50:33 GMT amqp10:client Decoding a315782d6f70742d73657175656e63652d6e756d626572
Mon, 02 Nov 2015 14:50:33 GMT amqp10:client Decoding 810000000000000086
Mon, 02 Nov 2015 14:50:33 GMT amqp10:client Reading variable with prefix 0xa0 of length 14
Mon, 02 Nov 2015 14:50:33 GMT amqp10:client Decoding a30c782d6f70742d6f6666736574
Mon, 02 Nov 2015 14:50:33 GMT amqp10:client Reading variable with prefix 0xa0 of length 8
Mon, 02 Nov 2015 14:50:33 GMT amqp10:client Decoding a106373536343732
Mon, 02 Nov 2015 14:50:33 GMT amqp10:client Reading variable with prefix 0xa0 of length 21
Mon, 02 Nov 2015 14:50:33 GMT amqp10:client Decoding a313782d6f70742d656e7175657565642d74696d65
Mon, 02 Nov 2015 14:50:33 GMT amqp10:client Decoding 8300000150a50ffdee
Mon, 02 Nov 2015 14:50:33 GMT amqp10:client Reading variable with prefix 0xb0 of length 258024
malformed payload: Unable to decode bytes from message body: 005375b00003efe35b7b226576656e7474797065223a2254656c656d65747279....

-------------------------------------------------------------------------------------------------------

Mon, 02 Nov 2015 14:50:32 GMT amqp10:client Decoding a315782d6f70742d73657175656e63652d6e756d626572
Mon, 02 Nov 2015 14:50:32 GMT amqp10:client Decoding 810000000000000089
Mon, 02 Nov 2015 14:50:32 GMT amqp10:client Reading variable with prefix 0xa0 of length 14
Mon, 02 Nov 2015 14:50:32 GMT amqp10:client Decoding a30c782d6f70742d6f6666736574
Mon, 02 Nov 2015 14:50:32 GMT amqp10:client Reading variable with prefix 0xa0 of length 8
Mon, 02 Nov 2015 14:50:32 GMT amqp10:client Decoding a106373333343536
Mon, 02 Nov 2015 14:50:32 GMT amqp10:client Reading variable with prefix 0xa0 of length 21
Mon, 02 Nov 2015 14:50:32 GMT amqp10:client Decoding a313782d6f70742d656e7175657565642d74696d65
Mon, 02 Nov 2015 14:50:32 GMT amqp10:client Decoding 8300000150a5102c49
Mon, 02 Nov 2015 14:50:32 GMT amqp10:client Reading variable with prefix 0xb0 of length 67529
malformed payload: Unable to decode bytes from message body: 005375b0000107c45b7b226576656e7474797065223a2254656c656d65747279....
```

Here's a good message that decodes fine:

```
Mon, 02 Nov 2015 14:50:16 GMT amqp10:client Reading variable with prefix 0xa0 of length 21
Mon, 02 Nov 2015 14:50:16 GMT amqp10:client Decoding a313782d6f70742d656e7175657565642d74696d65
Mon, 02 Nov 2015 14:50:16 GMT amqp10:client Decoding 830000015096221fbc
Mon, 02 Nov 2015 14:50:16 GMT amqp10:client Reading variable with prefix 0xb0 of length 11525
Mon, 02 Nov 2015 14:50:16 GMT amqp10:client Decoding 5375
Mon, 02 Nov 2015 14:50:16 GMT amqp10:client Decoding b000002d005b7b226576656e7474797065223a2254656c656d65747279507573684576656e74222c22706172746974696f6e6b6579223a[a_few_more_bytes_here_redacted]
Mon, 02 Nov 2015 14:50:16 GMT amqp10:session processing frame(TransferFrame): {"frameType":0,"channel":0,"handle":0,"deliveryId":0,"deliveryTag":{"type":"Buffer","data":[]},"messageFormat":0,"settled":true,"more
Mon, 02 Nov 2015 14:50:16 GMT amqp10:link:receiver Rx message 0 on xx-xxxxxx-xxxxx-xxx/ConsumerGroups/$default/Partitions/00_xxxxx-xxxxxx-xxxxxxxxx-xxxxxxx, 99 credit, 299 window left.
Mon, 02 Nov 2015 14:50:16 GMT amqp10:framing:amqp Encoding performative: {"descriptor":{"buffer":{"type":"Buffer","data":[0,0,0,0,0,0,0,21]},"offset":0},"value":{"role":true,"first":{"typeName":"uint","value":0}
Mon, 02 Nov 2015 14:50:16 GMT amqp10:framing Sending frame: DispositionFrame: {"type":"Buffer","data":[0,0,0,23,2,0,0,1,0,83,21,192,10,6,65,67,67,65,0,83,36,69,66]}: 0000001702000001005315c00a0641434341005324454
Mon, 02 Nov 2015 14:50:16 GMT amqp10:link:receiver received from (xx-xxxxx-xxxxx-xxx/ConsumerGroups/$default/Partitions/00_xxxxxxx-xxxxxx-xxxxxxx-xxxxxxxx): [object Object],[object Object],[object Object]


Recv(0):
msg =  { body:
   [ { eventtype: 'TelemetryPushEvent',...
```

**Comment by noodlefrenzy** [comment]
So just to verify I'm understanding this correctly - you're seeing some messages decode successfully, and those seem to be below a certain size, but larger ones are failing. I'll write an end-to-end test to see if I can repro on my end with a large payload message.

**Comment by snobu** [comment]
That seems about right. Looks like every message that fails decoding is above 64KB. I'm more and more confident these large messages are neither corrupt or the result of the decoder tripping and mushing together a bunch of smaller messages. There' only one occurrence of `[`, and the payload validates as valid JSON when decoded manually from the Exception output.

```bash
15:50:48 [root@u15 node-amqp10]# grep "\[" isolate.json
[
```

**Comment by noodlefrenzy** [comment]
This is almost certainly due to large messages being broken up into multiple transfer frames by Event Hub. Our code doesn't support split-frame messages currently (as we've never needed it), and Event Hub is the one enforcing the 64k maximum frame size and forcing themselves to split.

However, that doesn't help you any :( . I now have a repro case, and once I verify explicitly that it's sending valid multi-frame messages I'll start working on multi-frame message support. In the short-term, however, if there's a way to ensure your messages don't go above EH's frame limit, they should operate successfully with our code.

**Comment by noodlefrenzy** [comment]
They _are_ sending a multi-frame payload, but the second transfer frame _appears_ to be malformed:
`0x005314c00d0b520740404040424040404040657931...`

I'll reach out to the Service Bus team and see if there's an issue on their end or if it's (the more likely) a PEBKAC issue on my end.

**Comment by snobu** [comment]
@noodlefrenzy Thank you for your time and efforts looking into this.

**Comment by noodlefrenzy** [comment]
No worries, I'm just sorry it's not going to be a simple fix. It apparently is a PEBKAC issue on my end - for multi-frame transfers I need to basically stall the parsing until I receive all transfer frames, and only then process the whole shebang as the message payload - that'll take some time and thought to implement.

**Comment by noodlefrenzy** [comment]
I'll be tracking the actual work to support this feature in #185 to avoid spamming this issue with sausage-making details.

**Comment by mbroadst** [comment]
@ianwsperber @snobu: we've landed preliminary support for multi-frame messages in the `multi-frame-messages` branch (go figure). This should hopefully resolve the issue you've seen. If you want to try it out before we merge then you need simply update your `package.json` accordingly:

```
"dependencies": {
   ... other deps ...
   "amqp10": "noodlefrenzy/node-amqp10#multi-frame-messages"
}
```

**Comment by mbroadst** [comment]
Hey guys, we actually felt that with unit tests around the feature, as well as integration tests against EH and Qpid that we would go ahead and merge it in and publish a minor point release. Please give it a shot with version `2.1.0` (you will automatically get this if you're using `^2.0.0`). Thanks.

**Comment by ianwsperber** [comment]
Sorry for dropping out of this - this issue was deprioritized at work and I haven't had any free time otherwise.

I just installed version 2.1.0 into our stream processor and it worked perfectly. Can't emphasize how much I appreciate everyone's help with this!

After I've run some more thorough benchmarks/tests on my own I'll be pushing to have this integrated into our stream processing system in the near future. Are there any rough spots we should keep an eye on?

**Comment by snobu** [comment]
Holy moley! This is the fastest development cycle I've witness.. from bug isolation to fully working patch in under 2 days.

I've run the same batch of messages through the newly commited code and every single message now decodes successfully.

Superb job @mbroadst @noodlefrenzy.

**Comment by mbroadst** [comment]
Glad to hear it works guys :+1: 

@ianwsperber we try to keep a semi up-to-date list of [known issues](https://github.com/noodlefrenzy/node-amqp10#todos-and-known-issues), but generally the rough spots are in line with "the rough spots of using JavaScript". Stuff like the lack of large number support (we overcome this with `node-int64`, but the numbers are still best represented as strings when sufficiently large), utf32be isn't really supported as you saw the other day because we're using UTF-16/UCS2 under the hood, etc. 

Performance is pretty good (basic benchmark on #138), and I'm working a little bit now on optimizing the codebase with v8's traceopt flags so that should get better. Besides that, the module is used daily in production in a product I work on and I haven't noticed a single glitch in the past five months of continuous use - I'd say it's pretty stable. Having said that I don't use it with SB/EH, but I gather other users have seen similar results in their use of the module with those services

**Comment by mbroadst** [comment]
I'm going to go ahead and close this out now, please feel free to reopen if you feel this isn't completely solved.
