### ISSUE TITLE
Error sending message: AmqpProtocolError: com.microsoft:timeout:The operation did not complete within the allotted timeout of 00:01:00.

### ISSUE THREAD

**Issue by gjr-qm** [noodlefrenzy/node-amqp10#299]
After 6 months with no problems using node-amqp10 (version 3.2.2) in production last Friday suddenly errors occurred when sending messages to ASB topics.

The problem is that the errors occur on sender level (on errorReceived ) and not on when calling send (rejected promise). My code:

```
...
let topicSender = amqpTopicClient.createSender(topicSend).then((sender) => {
    sender.on('errorReceived', function(tx_err) {
        if (tx_err.condition && (tx_err.condition == 'amqp:link:detach-forced')) {
            amqpTopicClient.disconnect().then(function () {
                sender = null;
                logger.info(`Disconnected due to timeout (${topicSend})`);
            });
        }
        else {
            logger.error(`${queueSend} ===> TX ERROR: `, tx_err);                    
        }
    });
    done(null, sender);
    return null;
});
```

and sending the messages with:

```
topicSender.send(message).then(function(state) {
    // this can be used to optionally track the disposition of the sent message
    logger.info(`Message ${message.properties.messageId} sent.`);
    logger.info(`result ` + util.inspect(state));    
})
.error(function(error) {
    logger.error('send error: ', error);
});

```

The .error (promise rejection) is never called and my problem is that in the 'errorReceived' event I do not have info about the message that failed.  Restarting the app solved the problem at first, but right now another queue/topic starts throwing the same error (with the same trackingId).

Any idea what the best way is to handle this problem?

**Comment by mbroadst** [comment]
@gjr-qm Hi, can you confirm that your `SenderLink` callback policy (`policy.callback`) is 'sent` (or `SenderCallbackPolicies.OnSent`)?  As you can see [here](https://github.com/noodlefrenzy/node-amqp10/blob/master/lib/sender_link.js#L138), if that is the case then the sent message will resolve as soon as we send the message, rather than waiting for disposition (or errors) to occur.

**Comment by gjr-qm** [comment]
We're creating the AMQPClient like this:

```
new AMQPClient(Policy.ServiceBusTopic)
```

I didn't check before, but the default of policy.callback is OnSettle if I'm correct? I do think that is the case because the promise (.then) is never resolved. My hope was that the timeout would result in a rejection of the promise, so we could handle it in the .error part of the code.

**Comment by mbroadst** [comment]
@gjr-qm hm yes, it should indeed reject if it receives that error. I wonder if you're receiving disposition and _then_ receiving an error? Could you potentially post some logs for a reproduction of this case? I'll look into seeing if there's a bug on our side.

**Comment by mbroadst** [comment]
@gjr-qm in particular it would be incredibly helpful to see if you are in fact getting a `disposition` _before_ the error occurs.

**Comment by gjr-qm** [comment]
I will dive into the logs. At the moment our queues are running fine again and of course, we don't run with full debug logs during normal operation. But I think I can reconstruct the important parts from the normal logs. As far as I can see we were not getting any `disposition` on the faulty queue. Looks like the timeout error on the queue is the only thing we're getting.

Back to the logs...

**Comment by gjr-qm** [comment]
I've been going through a lot of log files and didn't find any send promise rejected. So I think the conclusion is that de client emits an `errorReceived` but no `disposition` (or send error) occurs.

**Comment by gjr-qm** [comment]
Maybe a stack trace helps?

```
AmqpProtocolError: com.microsoft:timeout:The operation did not complete within the allotted timeout of 00:01:00. The time allotted to this operation may have been a portion of a longer timeout. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101 TrackingId:8b93a7aeeccf45c7b8ec1077f7bb2ed8_G58, SystemTracker:gateway6, Timestamp:2/27/2017 8:42:18 AM
    at Object.utilities.wrapProtocolError (/bundle/bundle/programs/server/npm/npm-container/node_modules/amqp10/lib/utilities.js:273:12)
    at SenderLink.Link._detached (/bundle/bundle/programs/server/npm/npm-container/node_modules/amqp10/lib/link.js:207:37)
    at SenderLink._detached (/bundle/bundle/programs/server/npm/npm-container/node_modules/amqp10/lib/sender_link.js:210:41)
    at SenderLink.Link._detachReceived (/bundle/bundle/programs/server/npm/npm-container/node_modules/amqp10/lib/link.js:192:8)
    at Session._processDetachFrame (/bundle/bundle/programs/server/npm/npm-container/node_modules/amqp10/lib/session.js:337:45)
    at Session._processFrame (/bundle/bundle/programs/server/npm/npm-container/node_modules/amqp10/lib/session.js:304:61)
    at Connection._processFrameEH (/bundle/bundle/programs/server/npm/npm-container/node_modules/amqp10/lib/session.js:186:49)
    at Connection.emit (events.js:117:20)
    at Connection._receiveAny (/bundle/bundle/programs/server/npm/npm-container/node_modules/amqp10/lib/connection.js:431:16)
    at Connection._receiveData (/bundle/bundle/programs/server/npm/npm-container/node_modules/amqp10/lib/connection.js:362:8)
    at [object Object].<anonymous> (/bundle/bundle/programs/server/npm/npm-container/node_modules/amqp10/lib/connection.js:521:10)
    at [object Object].emit (events.js:95:17)
    at CleartextStream.<anonymous> (/bundle/bundle/programs/server/npm/npm-container/node_modules/amqp10/lib/transport/tls_transport.js:28:48)
    at CleartextStream.emit (events.js:95:17)
    at CleartextStream.<anonymous> (_stream_readable.js:765:14)
    at CleartextStream.emit (events.js:92:17)

```

**Comment by gjr-qm** [comment]
This morning the error appeared again. I restarted the system with `DEBUG=amqp10:se*` to get sender and session debug info. Is that ok, or should I choose a different debug target? I was afraid a full debug (amqp*) would be an overkill for this problem...

**Comment by mbroadst** [comment]
@gjr-qm I usually do a full `amqp*`, if you feel like that's too much info you might do `session*`/`sender*`/`link*`

**Comment by gjr-qm** [comment]
Our system is running with the new debug config now. No errors so far...

Now let's hope the error surfaces again soon because I prefer a fix rather than concluding (again) that this was another Azure/MS hickup.

I'll close this one for now and will reopen it when the error pops up again.

@mbroadst: thanks again for your help/support!

**Comment by gjr-qm** [comment]
Last week (and tonight) the error occurred again...

I had to clean up the logs, because we have quite a few topics and queues and there was only one that went wrong.

Here are the important parts of the log:

**last correct send**
```
Thu, 02 Mar 2017 10:48:56 GMT amqp10:session Transitioning from UNMAPPED to BEGIN_SENT due to sendBegin
Thu, 02 Mar 2017 10:48:56 GMT amqp10:session processing frame:  @begin(17) [remoteChannel=1 nextOutgoingId=1 incomingWindow=5000 outgoingWindow=100 handleMax=255 offeredCapabilities=null desiredCapabilities=null properties={}]
Thu, 02 Mar 2017 10:48:56 GMT amqp10:session Transitioning from BEGIN_SENT to MAPPED due to beginReceived
Thu, 02 Mar 2017 10:48:56 GMT amqp10:session On BEGIN_RCVD, setting params to (1,5000,100,255)
Thu, 02 Mar 2017 10:48:56 GMT amqp10:link undefined:0: Transitioning from DETACHED to ATTACHING due to sendAttach
Thu, 02 Mar 2017 10:48:56 GMT amqp10:link attach CH=1, Handle=0
Thu, 02 Mar 2017 10:48:56 GMT amqp10:session processing frame:  @attach(18) [name='faulty.topic.write_xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' handle=0 role=true sndSettleMode=2 rcvSettleMode=0 source=@source(40) [address='localhost' durable=0 expiryPolicy='session-end' timeout=0 dynamic=false dynamicNodeProperties={} distributionMode=null filter={} defaultOutcome=null outcomes=null capabilities=null] target=@target(41) [address='faulty.topic.write' durable=0 expiryPolicy='session-end' timeout=0 dynamic=false dynamicNodeProperties={} capabilities=null] unsettled=null incompleteUnsettled=null initialDeliveryCount=null maxMessageSize=10000 offeredCapabilities=null desiredCapabilities=null properties={}]
Thu, 02 Mar 2017 10:48:56 GMT amqp10:link faulty.topic.write_xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx:0: Transitioning from ATTACHING to ATTACHED due to attachReceived
Thu, 02 Mar 2017 10:48:56 GMT amqp10:link faulty.topic.write_xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx: attached CH=[1=>0], Handle=[0=>0]
Thu, 02 Mar 2017 10:48:56 GMT amqp10:link:sender canSend(0,5000) = false
Thu, 02 Mar 2017 10:48:56 GMT amqp10:session processing frame:  @flow(19) [nextIncomingId=1 incomingWindow=5000 nextOutgoingId=1 outgoingWindow=100 handle=0 deliveryCount=0 linkCredit=1000 available=0 drain=null echo=false properties=null]
Thu, 02 Mar 2017 10:48:56 GMT amqp10:session New Incoming Window (known id): 5000 = 1 + 5000 - 1
Thu, 02 Mar 2017 10:48:56 GMT amqp10:link:sender setting credits (1000,5000)
Thu, 02 Mar 2017 10:48:56 GMT amqp10:link:sender canSend(1000,5000) = true
Thu, 02 Mar 2017 10:48:56 GMT amqp10:link:sender sending:  { applicationProperties: 
   { MessageTime: '10:48:56' },
  properties: 
   { messageId: '13f2bc041463417da10a45a3bca9cf4f',
     contentType: 'text/xml' },
  body: <Buffer ...> }
Thu, 02 Mar 2017 10:48:56 GMT amqp10:session processing frame:  @disposition(21) [role=true first=1 last=null settled=true state=@accepted(36) [] batchable=null]
```
**timeout**
```
Thu, 02 Mar 2017 10:58:56 GMT amqp10:session processing frame:  @detach(22) [handle=0 closed=true error=@error(29) [condition='amqp:link:detach-forced' description='The link \'G35:7010626:faulty.topic.write_xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx\' is force detached by the broker due to errors occurred in publisher(link307686). Detach origin: AmqpMessagePublisher.IdleTimerExpired: Idle timeout: 00:10:00. TrackingId:23a8c62f000057e70004b1e658b7f898_G35_B2, SystemTracker:yyyyyyy:Topic:faulty.topic.write, Timestamp:3/2/2017 10:58:57 AM' info=null]]
Thu, 02 Mar 2017 10:58:56 GMT amqp10:link faulty.topic.write_xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx:0: Transitioning from ATTACHED to DETACHING due to detachReceived
Thu, 02 Mar 2017 10:58:56 GMT amqp10:link faulty.topic.write_xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx:0: Transitioning from DETACHING to DETACHED due to detached
Thu, 02 Mar 2017 10:58:56 GMT amqp10:session detached(faulty.topic.write_xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx): AmqpProtocolError: amqp:link:detach-forced:The link 'G35:7010626:faulty.topic.write_xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx' is force detached by the broker due to errors occurred in publisher(link307686). Detach origin: AmqpMessagePublisher.IdleTimerExpired: Idle timeout: 00:10:00. TrackingId:23a8c62f000057e70004b1e658b7f898_G35_B2, SystemTracker:yyyyyyy:Topic:faulty.topic.write, Timestamp:3/2/2017 10:58:57 AM
Thu, 02 Mar 2017 10:58:56 GMT amqp10:link faulty.topic.write_xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx:0: Transitioning from DETACHED to REATTACHING due to reattach
Thu, 02 Mar 2017 10:58:56 GMT amqp10:link Attempting to reattach faulty.topic.write_xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
Thu, 02 Mar 2017 10:58:56 GMT amqp10:link attach CH=1, Handle=0
```
**here's where it goes wrong**
```
Thu, 02 Mar 2017 11:07:06 GMT amqp10:session Transitioning from UNMAPPED to BEGIN_SENT due to sendBegin
Thu, 02 Mar 2017 11:07:06 GMT amqp10:session processing frame:  @begin(17) [remoteChannel=1 nextOutgoingId=1 incomingWindow=5000 outgoingWindow=100 handleMax=255 offeredCapabilities=null desiredCapabilities=null properties={}]
Thu, 02 Mar 2017 11:07:06 GMT amqp10:session Transitioning from BEGIN_SENT to MAPPED due to beginReceived
Thu, 02 Mar 2017 11:07:06 GMT amqp10:session On BEGIN_RCVD, setting params to (1,5000,100,255)
Thu, 02 Mar 2017 11:07:06 GMT amqp10:link undefined:0: Transitioning from DETACHED to ATTACHING due to sendAttach
Thu, 02 Mar 2017 11:07:06 GMT amqp10:link attach CH=1, Handle=0
Thu, 02 Mar 2017 11:07:35 GMT amqp10:session processing frame:  @transfer(20) [handle=0 deliveryId=575 deliveryTag=<Buffer 3f f2 cc 83 af a1 a3 49 b9 a9 79 4a d0 73 22 22> messageFormat=0 settled=null more=false rcvSettleMode=null state=null resume=null aborted=null batchable=true]
Thu, 02 Mar 2017 11:08:06 GMT amqp10:session processing frame:  @attach(18) [name='faulty.topic.write_b741de1a-e4b2-45fc-b7b0-e3193e0d2ae6' handle=0 role=true sndSettleMode=2 rcvSettleMode=0 source=null target=null unsettled=null incompleteUnsettled=null initialDeliveryCount=null maxMessageSize=10000 offeredCapabilities=null desiredCapabilities=null properties={}]
Thu, 02 Mar 2017 11:08:06 GMT amqp10:link faulty.topic.write_b741de1a-e4b2-45fc-b7b0-e3193e0d2ae6:0: Transitioning from ATTACHING to ATTACHED due to attachReceived
Thu, 02 Mar 2017 11:08:06 GMT amqp10:link faulty.topic.write_b741de1a-e4b2-45fc-b7b0-e3193e0d2ae6: attached CH=[1=>0], Handle=[0=>0]
Thu, 02 Mar 2017 11:08:06 GMT amqp10:link:sender canSend(0,5000) = false
Thu, 02 Mar 2017 11:08:06 GMT amqp10:session processing frame:  @detach(22) [handle=0 closed=true error=@error(29) [condition='com.microsoft:timeout' description='The operation did not complete within the allotted timeout of 00:01:00. The time allotted to this operation may have been a portion of a longer timeout. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101 TrackingId:8b93a7aeeccf45c7b8ec1077f7bb2ed8_G58, SystemTracker:gateway6, Timestamp:3/2/2017 11:08:06 AM' info=null]]
Thu, 02 Mar 2017 11:08:06 GMT amqp10:link faulty.topic.write_b741de1a-e4b2-45fc-b7b0-e3193e0d2ae6:0: Transitioning from ATTACHED to DETACHING due to detachReceived
Thu, 02 Mar 2017 11:08:06 GMT amqp10:link faulty.topic.write_b741de1a-e4b2-45fc-b7b0-e3193e0d2ae6:0: Transitioning from DETACHING to DETACHED due to detached
Thu, 02 Mar 2017 11:08:06 GMT amqp10:session detached(faulty.topic.write_b741de1a-e4b2-45fc-b7b0-e3193e0d2ae6): AmqpProtocolError: com.microsoft:timeout:The operation did not complete within the allotted timeout of 00:01:00. The time allotted to this operation may have been a portion of a longer timeout. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101 TrackingId:8b93a7aeeccf45c7b8ec1077f7bb2ed8_G58, SystemTracker:gateway6, Timestamp:3/2/2017 11:08:06 AM
Thu, 02 Mar 2017 11:08:06 GMT amqp10:link faulty.topic.write_b741de1a-e4b2-45fc-b7b0-e3193e0d2ae6:0: Transitioning from DETACHED to REATTACHING due to reattach
Thu, 02 Mar 2017 11:08:06 GMT amqp10:link Attempting to reattach faulty.topic.write_b741de1a-e4b2-45fc-b7b0-e3193e0d2ae6
Thu, 02 Mar 2017 11:08:06 GMT amqp10:link attach CH=1, Handle=0
```

After that, every minute the system tries to reattach `@attach(18)` again, but it never succeeds. Restarting the application solves the problem, attaching to the faulty topic is no problem.

What is the best way to handle this error? Because the send promise is never resolved or rejected and the error occurs on the link (and not in the send function).

**Comment by gjr-qm** [comment]
As I said before, the strange thing is that the application ran without this problem for over 6 months. We didn't change anything and suddenly this error pops up. I think there must be something that has changed on the Azure side...

**Comment by mbroadst** [comment]
@gjr-qm there is definitely some change in the server. We're tracking a reattachment issue over on #295. You might want to try out using the case in the [issue295](https://github.com/noodlefrenzy/node-amqp10/tree/issue295) branch, as I have pushed some fixes there related to link reattachment.  

As far as I can tell from the logs you've provided this looks very much like a problem on Microsoft's end. The exception being thrown is related to a _remote_ operation failing to complete in the allotted time, and the link to their documentation indicates changes in e.g. `OperationTimeout` which would be a remotely configured parameter. I suggest reaching out to Microsoft to see if they have been seeing any similar error reports.

Regarding reattachment failing, what _seems_ to be happening there is that you have no link credit:
```
Thu, 02 Mar 2017 11:08:06 GMT amqp10:link faulty.topic.write_b741de1a-e4b2-45fc-b7b0-e3193e0d2ae6:0: Transitioning from ATTACHING to ATTACHED due to attachReceived
Thu, 02 Mar 2017 11:08:06 GMT amqp10:link faulty.topic.write_b741de1a-e4b2-45fc-b7b0-e3193e0d2ae6: attached CH=[1=>0], Handle=[0=>0]
Thu, 02 Mar 2017 11:08:06 GMT amqp10:link:sender canSend(0,5000) = false
```

But its unclear how you got to that state. I believe you're at very least missing logs for `amqp10:link:sender`/`amqp10:link:receiver`, it might be better to initially try `amqp*`.

**Comment by gjr-qm** [comment]
@mbroadst thanks for your response again!

I'll try `amqp*` for the logging. Btw, is it possible to get milliseconds in the log time stamp? Our log uses milliseconds because a lot can happen within a second these days...

This error is very frustrating because it happens at random times and we don't have an automated solution to handle it at the moment. We have to continuously keep an eye on the logs now in our production environment.

I think we try a temporary solution and disconnect the topic when the error occurs. Then reconnect and send the message again (after some time has elapsed?). Do you think this can work?

I hope so because every time I restart the application things seem to work again.

Of course, we have to register the message as pending, because the error occurs on the link and not in the send function itself. Or will node-amqp10 handle this with the internal pending messages?

Still strange that the promise there is never resolved or rejected. Could that be an omission in node-amqp10?

**Comment by mbroadst** [comment]
@gjr-qm I don't see an easy way in `node-debug` to enable millisecond logging unfortunately, but you could manually modify the code and `console.log` whatever you want. 

> This error is very frustrating because it happens at random times and we don't have an automated solution to handle it at the moment. We have to continuously keep an eye on the logs now in our production environment.

Yes I understand this very well, it's very difficult for me to debug without being able to reproduce the problem locally myself :)

> I think we try a temporary solution and disconnect the topic when the error occurs. Then reconnect and send the message again (after some time has elapsed?). Do you think this can work?

Well this is basically what the driver does itself, it processes detachment of the link and then attempts reattachment. Somewhere in that process the credit is being screwed up, and subsequent operations are stalled until they are able to send again. Internally in node-amqp10 there already is a `pendingSends` array, which in your case is probably filling up with promises until there is enough credit to send messages (and this never happens, thus leading to a stall). 

Having said that, when a link is detached currently all pendingSends/unconfirmedSends are rejected out of hand with a `force:detach` error - so that should be enough to keep things moving along.  It will be very crucial for you to figure out exactly why you are running out of credit in order to solve this problem.

**Comment by gjr-qm** [comment]
Hmmm, didn't think of the credits being a possible source of the problem. And after looking through the code and logs, I still can't see that it could be.

I create the client like this: `new AMQPClient(Policy.Utils.RenewOnSettle(1, 1, Policy.ServiceBusQueue))`. In the application code, there is no reference to `credits` or `credit`. And the successful send log entries look like this:

```
amqp10:link:sender canSend(0,5000) = false
amqp10:session processing frame:  @flow(19) [nextIncomingId=1 incomingWindow=5000 nextOutgoingId=1 outgoingWindow=100 handle=0 deliveryCount=0 linkCredit=1000 available=0 drain=null echo=false properties=null]
amqp10:session New Incoming Window (known id): 5000 = 1 + 5000 - 1
amqp10:link:sender setting credits (1000,5000)
amqp10:link:sender canSend(1000,5000) = true
```

So every send (after attach) starts with 0 credits, but then 1000 credits are added. The difference between a successful send and one that is failing is that with the former a `@flow(19)` frame is processed while with the latter a `@detach(22)` follows the `canSend(0,5000)`.

**Comment by mbroadst** [comment]
@gjr-qm if you take a look at the log section I pasted above (and what you referred to _right_ at the end of your last comment here), the message is: `canSend(0,5000)`. That message is generated [here](https://github.com/noodlefrenzy/node-amqp10/blob/master/lib/sender_link.js#L46), and is essentially `(<link-credit>, <incoming-window>)` - so this means in that particular case you have no credit at all, and that looks suspiciously close to the failures cases in your above presented log.

**Comment by gjr-qm** [comment]
@mbroadst, I was mistaken in my previous post about how we create the client. This is how we create it:
`let amqpTopicClient = new AMQPClient(Policy.ServiceBusTopic);`.

I just did some testing and I think you're wrong about the credits. Here's the full log for a succesful send:
```
Mon, 06 Mar 2017 22:09:23 GMT amqp10:client connecting to: amqps://yyyy@xxxx.servicebus.windows.net
Mon, 06 Mar 2017 22:09:23 GMT amqp10:transport:tls Connecting to xxxx.servicebus.windows.net:5671 via TLS
Mon, 06 Mar 2017 22:09:23 GMT amqp10:connection Transitioning from DISCONNECTED to START due to connect
Mon, 06 Mar 2017 22:09:23 GMT amqp10:connection Sending Header 414d515003010000
Mon, 06 Mar 2017 22:09:23 GMT amqp10:connection Transitioning from START to IN_SASL due to connected
Mon, 06 Mar 2017 22:09:23 GMT amqp10:connection Rx: 414d515003010000
Mon, 06 Mar 2017 22:09:23 GMT amqp10:sasl Server SASL Version: 414d515003010000 vs 414d515003010000
Mon, 06 Mar 2017 22:09:23 GMT amqp10:connection Rx: 0000003f02010000005340c03201e02f04b3000000074d53534243425300000005504c41494e00000009414e4f4e594d4f55530000000845585445524e414c
Mon, 06 Mar 2017 22:09:23 GMT amqp10:sasl Sending asb-topic.send:xfWANSfRiWkCuLhzBYKQKsoPzVHWWXtNmca2oRAHqDc=
Mon, 06 Mar 2017 22:09:23 GMT amqp10:framing sending frame:  @sasl-init(65) [mechanism='PLAIN' initialResponse=<Buffer 00 68 72 6d 6c 2e 72 65 70 6f 72 74 2e 77 72 69 74 65 2e 73 65 6e 64 00 78 66 57 41 4e 53 66 52 69 57 6b 43 75 4c 68 7a 42 59 4b 51 4b 73 6f 50 7a 56 48 ...> hostname=null] : 0000005c02010000005341c04f03a305504c41494ea0440068726d6c2e7265706f72742e77726974652e73656e6400786657414e53665269576b43754c687a42594b514b736f507a5648575758744e6d6361326f5241487144633d40
Mon, 06 Mar 2017 22:09:23 GMT amqp10:connection Rx: 0000001a02010000005344c00d025000a00857656c636f6d6521
Mon, 06 Mar 2017 22:09:23 GMT amqp10:connection Sending Header 414d515000010000
Mon, 06 Mar 2017 22:09:23 GMT amqp10:connection Transitioning from IN_SASL to HDR_SENT due to success
Mon, 06 Mar 2017 22:09:23 GMT amqp10:connection Rx: 414d515000010000
Mon, 06 Mar 2017 22:09:23 GMT amqp10:connection Server AMQP Version: 414d515000010000 vs 414d515000010000
Mon, 06 Mar 2017 22:09:23 GMT amqp10:connection Transitioning from HDR_SENT to HDR_EXCH due to validVersion
Mon, 06 Mar 2017 22:09:23 GMT amqp10:framing sending frame:  @open(16) [containerId='conn1488838163364' hostname='xxxx.servicebus.windows.net' maxFrameSize=4294967295 channelMax=65535 idleTimeout=120000 outgoingLocales='en-US' incomingLocales='en-US' offeredCapabilities=null desiredCapabilities=null properties={}] : 0000006302000000005310c0560aa111636f6e6e31343838383338313633333634a120676974702d617362612e736572766963656275732e77696e646f77732e6e657470ffffffff60ffff700001d4c0a305656e2d5553a305656e2d55534040c10100
Mon, 06 Mar 2017 22:09:23 GMT amqp10:connection Transitioning from HDR_EXCH to OPEN_SENT due to sendOpen
Mon, 06 Mar 2017 22:09:23 GMT amqp10:connection Rx: 0000004702000000005310c03a0aa12435346532313734383238373134353037393161373563626666646538616530375f473539407000010000601387700003a9804040404040
Mon, 06 Mar 2017 22:09:23 GMT amqp10:connection Transitioning from OPEN_SENT to OPENED due to openReceived
Mon, 06 Mar 2017 22:09:23 GMT amqp10:connection Connected with params { maxFrameSize=65536, channelMax=4999, idleTimeout=120000 }
Mon, 06 Mar 2017 22:09:23 GMT amqp10:connection Setting heartbeat check timeout to 15000
Mon, 06 Mar 2017 22:09:23 GMT amqp10:client connected
Mon, 06 Mar 2017 22:09:23 GMT amqp10:session Transitioning from UNMAPPED to BEGIN_SENT due to sendBegin
Mon, 06 Mar 2017 22:09:23 GMT amqp10:framing sending frame:  @begin(17) [remoteChannel=null nextOutgoingId=1 incomingWindow=100 outgoingWindow=100 handleMax=4294967295 offeredCapabilities=null desiredCapabilities=null properties={}] : 0000001f02000001005311c012084052015264526470ffffffff4040c10100
Mon, 06 Mar 2017 22:09:23 GMT amqp10:connection Rx: 0000002102000000005311c0140860000152017000001388526452ff4040c10100
Mon, 06 Mar 2017 22:09:23 GMT amqp10:session processing frame:  @begin(17) [remoteChannel=1 nextOutgoingId=1 incomingWindow=5000 outgoingWindow=100 handleMax=255 offeredCapabilities=null desiredCapabilities=null properties={}]
Mon, 06 Mar 2017 22:09:23 GMT amqp10:session Transitioning from BEGIN_SENT to MAPPED due to beginReceived
Mon, 06 Mar 2017 22:09:23 GMT amqp10:session On BEGIN_RCVD, setting params to (1,5000,100,255)
Mon, 06 Mar 2017 22:09:23 GMT amqp10:client mapped
Mon, 06 Mar 2017 22:09:23 GMT amqp10:link undefined:0: Transitioning from DETACHED to ATTACHING due to sendAttach
Mon, 06 Mar 2017 22:09:23 GMT amqp10:link attach CH=1, Handle=0
Mon, 06 Mar 2017 22:09:23 GMT amqp10:framing sending frame:  @attach(18) [name='asb-topic_cfd3faf7-9dd7-4b88-969c-1af1059f9c16' handle=0 role=false sndSettleMode=2 rcvSettleMode=0 source=@source(40) [address='localhost' durable=0 expiryPolicy='session-end' timeout=0 dynamic=false dynamicNodeProperties={} distributionMode=null filter={} defaultOutcome=null outcomes=null capabilities=null] target=@target(41) [address='asb-topic' durable=0 expiryPolicy='session-end' timeout=0 dynamic=false dynamicNodeProperties={} capabilities=null] unsettled={} incompleteUnsettled=false initialDeliveryCount=1 maxMessageSize=10000 offeredCapabilities=null desiredCapabilities=null properties={}] : 000000b802000001005312c0ab0ea13668726d6c2e7265706f72742e77726974655f63666433666166372d396464372d346238382d393639632d316166313035396639633136434250025000005328c0260ba1096c6f63616c686f737443a30b73657373696f6e2d656e644342c1010040c10100404040005329c02807a11168726d6c2e7265706f72742e777269746543a30b73657373696f6e2d656e644342c1010040c101004252018000000000000027104040c10100
Mon, 06 Mar 2017 22:09:23 GMT amqp10:connection Rx: 000000b502000000005312c0a80ea13668726d6c2e7265706f72742e77726974655f63666433666166372d396464372d346238382d393639632d316166313035396639633136434150025000005328c0260ba1096c6f63616c686f737443a30b73657373696f6e2d656e644342c1010040c10100404040005329c02807a11168726d6c2e7265706f72742e777269746543a30b73657373696f6e2d656e644342c10100404040408000000000000027104040c10100
Mon, 06 Mar 2017 22:09:23 GMT amqp10:session processing frame:  @attach(18) [name='asb-topic_cfd3faf7-9dd7-4b88-969c-1af1059f9c16' handle=0 role=true sndSettleMode=2 rcvSettleMode=0 source=@source(40) [address='localhost' durable=0 expiryPolicy='session-end' timeout=0 dynamic=false dynamicNodeProperties={} distributionMode=null filter={} defaultOutcome=null outcomes=null capabilities=null] target=@target(41) [address='asb-topic' durable=0 expiryPolicy='session-end' timeout=0 dynamic=false dynamicNodeProperties={} capabilities=null] unsettled=null incompleteUnsettled=null initialDeliveryCount=null maxMessageSize=10000 offeredCapabilities=null desiredCapabilities=null properties={}]
Mon, 06 Mar 2017 22:09:23 GMT amqp10:link asb-topic_cfd3faf7-9dd7-4b88-969c-1af1059f9c16:0: Transitioning from ATTACHING to ATTACHED due to attachReceived
Mon, 06 Mar 2017 22:09:23 GMT amqp10:link asb-topic_cfd3faf7-9dd7-4b88-969c-1af1059f9c16: attached CH=[1=>0], Handle=[0=>0]
Mon, 06 Mar 2017 22:09:23 GMT amqp10:link:sender canSend(0,5000) = false
Mon, 06 Mar 2017 22:09:23 GMT amqp10:session processing frame:  @flow(19) [nextIncomingId=1 incomingWindow=5000 nextOutgoingId=1 outgoingWindow=100 handle=0 deliveryCount=0 linkCredit=1000 available=0 drain=null echo=false properties=null]
Mon, 06 Mar 2017 22:09:23 GMT amqp10:session New Incoming Window (known id): 5000 = 1 + 5000 - 1
Mon, 06 Mar 2017 22:09:23 GMT amqp10:link:sender setting credits (1000,5000)
Mon, 06 Mar 2017 22:09:23 GMT amqp10:link:sender canSend(1000,5000) = true
```

As you can see there is always the `sender canSend(0,5000) = false`, followed by a `@flow(19)` that results in setting the credits to 1000. The log above is when we connect with the default (Policy.ServiceBusTopic) policy and then just send a message. No additional settings or whatsoever.

I agree with you that the error is caused by changes on the Azure side that were made about two weeks ago (before that we never had this problem).

Still looking for a (temporary) solution that takes care of handling this error. As said before right now we have to watch the logs all the time, restart the application and resend the messages that went wrong.

As far as Microsoft support goes: we don't have a support contract with Microsoft and my experiences are not so good. That's why i try to solve it this way first.

**Comment by gjr-qm** [comment]
Oops, missed a few lines from the log. Here are the lines following the `canSend(1000,5000) = true`:

```
Mon, 06 Mar 2017 22:09:23 GMT amqp10:link:sender sending:  { 
  applicationProperties: { 
    MessageTime: '22:09:23' 
  },
  properties: { 
    messageId: '17ad1b2f280d4d218842e561ffef29f3',
    contentType: 'text/xml' 
  },
  body: <Buffer blahblah ...> 
}
Mon, 06 Mar 2017 22:09:23 GMT amqp10:framing sending frame:  @transfer(20) [handle=0 deliveryId=1 deliveryTag=<Buffer 31> messageFormat=0 settled=false more=false rcvSettleMode=0 state=null resume=false aborted=false batchable=false] : blahblah
Mon, 06 Mar 2017 22:09:23 GMT amqp10:connection Rx: 0000001802000000005315c00b0641520140410053244540
Mon, 06 Mar 2017 22:09:23 GMT amqp10:session processing frame:  @disposition(21) [role=true first=1 last=null settled=true state=@accepted(36) [] batchable=null]
```

**Comment by mbroadst** [comment]
@gjr-qm Oh I see, sorry we were missing the other context in your previous logs. Yes you will get a `canSend = false` when you locally run out of credit - I thought you were getting that message _after_ you completed the flow. My mistake.

I'm looking back on the issue here: can you confirm that you are getting an `errorReceived` every time this happens? Where are you getting that from? The connection or something else? That is very curious...

**Comment by gjr-qm** [comment]
We're getting the error from the sender: `sender.on('errorReceived', function(tx_err) {}`

**Comment by gjr-qm** [comment]
And yes when the topic goes 'faulty' the error persists. Every minute the sender attaches again, but the flow frame never gets in because of a timeout.

**Comment by mbroadst** [comment]
@gjr-qm Ah! Then I think this does look like a problem in our implementation. The spec tells us:

```
When an error occurs at a link endpoint, the endpoint MUST be detached with appropriate error information supplied in the error field of the detach frame. The link endpoint MUST then be destroyed. If any input (other than a detach) related to the endpoint either via the input handle or delivery-ids be received, the session MUST be terminated with an errant-link session-error. Since the link endpoint has been destroyed, the peer cannot reattach, and MUST resume the link in order to restore communication. In order to disambiguate the resume request from a pipelined re-attach the resuming attach performative MUST contain a non-null value for its unsettled field. Receipt of a pipelined attach MUST result in the session being terminated with an errant-link session-error.
```

So I actually think maybe the remote side is doing the right thing. It actually looks like when we receive these errors we need to close down the whole session, and reattempt a new connection to the server (or at least a new session).  I'll need some time to think about the implementation, but it shouldn't be too long. 

Thanks for sticking with me here :)

**Comment by gjr-qm** [comment]
Thank YOU for sticking with me! :)

I got really frustrated and was almost at the point of going back to a polling system. This is because our partners use Java and the standard Microsoft products (Navision) and couldn't do AMQP. And they don't have problems as far as I know.

Thanks again for the support you provide on node-amqp10!

**Comment by mbroadst** [comment]
@gjr-qm Is there any way you can provide me with the SB namespace name, and the topic name? I'm working through this issue presently with Microsoft. Perhaps you could email it to me, or DM me on the gitter channel?

**Comment by mbroadst** [comment]
@gjr-qm

Here was the response, looks like a bug on Microsoft's side:

"We have identified the bug in the service. For certain operations the timeout is not set appropriately, which could cause the operation to be stuck and subsequent calls to fail. The workaround is to create a new amqp connection that is likely handled by a different machine. If that does not work, the customer would need to contact the SB support to get the issue mitigated. The fix will be available in next deployment."

**Comment by gjr-qm** [comment]
@mbroadst thanks! Now I wonder of course when the next deployment is scheduled (and we can get some sleep). Do you know MS schedule for this?

**Comment by mbroadst** [comment]
@gjr-qm sorry no, I think you'll have to speak to MS about that

**Comment by gjr-qm** [comment]
Guess Microsoft fixed the bug since everything runs smooth again.

@mbroadst thanx again for your quick responses and help!
